services:
  - type: web
    name: your-rails-app
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mySite
          property: connectionString
    publishDirectory: ./public
